services:
  db:
    image: postgis/postgis:13-3.1
    container_name: postgres_postgis
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_postgis_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_postgis_data:
