services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres_user
      POSTGRES_PASSWORD: password
      #POSTGRES_DB: postgres_db # Optional
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: